const estudiantes = [
  // --- 1er Año ---
  {
    "cedula": "V-28123456",
    "nombre": "Juan",
    "apellidos": "Pérez",
    "materias": ["Matemáticas", "Ciencias Naturales", "Lengua y Literatura", "Educación Física", "Arte y Patrimonio"],
    "seccion": "A",
    "año": "1er Año",
    "genero": "Masculino",
    "estado": "Activo",
    "direccion": "Avenida Libertador, Res. Los Mangos, Torre A, Apto 1-1",
    "email": "juan.perez@example.com",
    "asistencias": { "matemáticas": 35, "ciencias naturales": 37, "lengua y literatura": 36, "educación física": 38, "arte y patrimonio": 34 },
    "notas": { "matemáticas": 15, "ciencias naturales": 18, "lengua y literatura": 16, "educación física": 19, "arte y patrimonio": 17 },
    "nombre_representante": "Pedro Pérez",
    "cedula_representante": "V-9123456",
    "fecha_nacimiento": "2011-05-20"
  },
  {
    "cedula": "V-28234567",
    "nombre": "Ana",
    "apellidos": "Rodríguez",
    "materias": ["Matemáticas", "Ciencias Naturales", "Lengua y Literatura", "Educación Física", "Arte y Patrimonio"],
    "seccion": "A",
    "año": "1er Año",
    "genero": "Femenino",
    "estado": "Activo",
    "direccion": "Calle 5, Urbanización La Florida, Casa 20",
    "email": "ana.rodriguez@example.com",
    "asistencias": { "matemáticas": 37, "ciencias naturales": 36, "lengua y literatura": 38, "educación física": 39, "arte y patrimonio": 35 },
    "notas": { "matemáticas": 17, "ciencias naturales": 16, "lengua y literatura": 18, "educación física": 20, "arte y patrimonio": 15 },
    "nombre_representante": "Isabel Rodríguez",
    "cedula_representante": "V-9234567",
    "fecha_nacimiento": "2011-02-10"
  },
  {
    "cedula": "V-28345678",
    "nombre": "Luis",
    "apellidos": "Martínez",
    "materias": ["Matemáticas", "Ciencias Naturales", "Lengua y Literatura", "Educación Física", "Arte y Patrimonio"],
    "seccion": "A",
    "año": "1er Año",
    "genero": "Masculino",
    "estado": "Activo",
    "direccion": "Avenida Sucre, Edificio El Valle, Apto 3-B",
    "email": "luis.martinez@example.com",
    "asistencias": { "matemáticas": 34, "ciencias naturales": 35, "lengua y literatura": 36, "educación física": 37, "arte y patrimonio": 33 },
    "notas": { "matemáticas": 14, "ciencias naturales": 15, "lengua y literatura": 17, "educación física": 18, "arte y patrimonio": 16 },
    "nombre_representante": "José Martínez",
    "cedula_representante": "V-9345678",
    "fecha_nacimiento": "2011-08-30"
  },
  {
    "cedula": "V-28456789",
    "nombre": "Sofía",
    "apellidos": "García",
    "materias": ["Matemáticas", "Ciencias Naturales", "Lengua y Literatura", "Educación Física", "Arte y Patrimonio"],
    "seccion": "A",
    "año": "1er Año",
    "genero": "Femenino",
    "estado": "Activo",
    "direccion": "Plaza El Carmen, Casa 8, Sector Central",
    "email": "sofia.garcia@example.com",
    "asistencias": { "matemáticas": 38, "ciencias naturales": 37, "lengua y literatura": 39, "educación física": 36, "arte y patrimonio": 38 },
    "notas": { "matemáticas": 19, "ciencias naturales": 17, "lengua y literatura": 19, "educación física": 17, "arte y patrimonio": 18 },
    "nombre_representante": "Laura García",
    "cedula_representante": "V-9456789",
    "fecha_nacimiento": "2011-11-12"
  },
  {
    "cedula": "V-28567890",
    "nombre": "Diego",
    "apellidos": "López",
    "materias": ["Matemáticas", "Ciencias Naturales", "Lengua y Literatura", "Educación Física", "Arte y Patrimonio"],
    "seccion": "A",
    "año": "1er Año",
    "genero": "Masculino",
    "estado": "Activo",
    "direccion": "Calle Los Apamates, Edif. Primavera, Piso 2",
    "email": "diego.lopez@example.com",
    "asistencias": { "matemáticas": 36, "ciencias naturales": 37, "lengua y literatura": 35, "educación física": 36, "arte y patrimonio": 38 },
    "notas": { "matemáticas": 16, "ciencias naturales": 18, "lengua y literatura": 15, "educación física": 16, "arte y patrimonio": 17 },
    "nombre_representante": "Marta López",
    "cedula_representante": "V-9567890",
    "fecha_nacimiento": "2011-01-25"
  },
  {
    "cedula": "V-27123456",
    "nombre": "Valentina",
    "apellidos": "Sánchez",
    "materias": ["Matemáticas", "Ciencias Naturales", "Lengua y Literatura", "Educación Física", "Historia de Venezuela"],
    "seccion": "B",
    "año": "1er Año",
    "genero": "Femenino",
    "estado": "Activo",
    "direccion": "Urbanización El Bosque, Vereda 3, Casa 15",
    "email": "valentina.sanchez@example.com",
    "asistencias": { "matemáticas": 38, "ciencias naturales": 37, "lengua y literatura": 39, "educación física": 38, "historia de venezuela": 38 },
    "notas": { "matemáticas": 18, "ciencias naturales": 17, "lengua y literatura": 16, "educación física": 19, "historia de venezuela": 15 },
    "nombre_representante": "Javier Sánchez",
    "cedula_representante": "V-8123456",
    "fecha_nacimiento": "2011-04-18"
  },
  {
    "cedula": "V-27234567",
    "nombre": "Carlos",
    "apellidos": "Díaz",
    "materias": ["Matemáticas", "Ciencias Naturales", "Lengua y Literatura", "Educación Física", "Historia de Venezuela"],
    "seccion": "B",
    "año": "1er Año",
    "genero": "Masculino",
    "estado": "Activo",
    "direccion": "Avenida Las Delicias, Quinta La Milagrosa",
    "email": "carlos.diaz@example.com",
    "asistencias": { "matemáticas": 36, "ciencias_naturales": 35, "lengua_y_literatura": 38, "educación_física": 37, "historia_de_venezuela": 37 },
    "notas": { "matemáticas": 16, "ciencias_naturales": 15, "lengua_y_literatura": 18, "educación_física": 17, "historia_de_venezuela": 19 },
    "nombre_representante": "Ana Díaz",
    "cedula_representante": "V-8234567",
    "fecha_nacimiento": "2011-07-22"
  },
  {
    "cedula": "V-27345678",
    "nombre": "Gabriela",
    "apellidos": "Ramírez",
    "materias": ["Matemáticas", "Ciencias Naturales", "Lengua y Literatura", "Educación Física", "Historia de Venezuela"],
    "seccion": "B",
    "año": "1er Año",
    "genero": "Femenino",
    "estado": "Activo",
    "direccion": "Final Calle El Progreso, Edif. Luna, Piso 4",
    "email": "gabriela.ramirez@example.com",
    "asistencias": { "matemáticas": 35, "ciencias_naturales": 36, "lengua_y_literatura": 35, "educación_física": 36, "historia_de_venezuela": 36 },
    "notas": { "matemáticas": 17, "ciencias_naturales": 19, "lengua_y_literatura": 17, "educación_física": 16, "historia_de_venezuela": 18 },
    "nombre_representante": "Miguel Ramírez",
    "cedula_representante": "V-8345678",
    "fecha_nacimiento": "2011-10-05"
  },
  {
    "cedula": "V-27456789",
    "nombre": "Andrés",
    "apellidos": "Torres",
    "materias": ["Matemáticas", "Ciencias Naturales", "Lengua y Literatura", "Educación Física", "Historia de Venezuela"],
    "seccion": "B",
    "año": "1er Año",
    "genero": "Masculino",
    "estado": "Activo",
    "direccion": "Sector La Candelaria, Calle Real, Casa #42",
    "email": "andres.torres@example.com",
    "asistencias": { "matemáticas": 37, "ciencias_naturales": 36, "lengua_y_literatura": 38, "educación_física": 37, "historia_de_venezuela": 37 },
    "notas": { "matemáticas": 15, "ciencias_naturales": 16, "lengua_y_literatura": 19, "educación_física": 18, "historia_de_venezuela": 17 },
    "nombre_representante": "Carmen Torres",
    "cedula_representante": "V-8456789",
    "fecha_nacimiento": "2011-12-30"
  },
  {
    "cedula": "V-27567890",
    "nombre": "Isabella",
    "apellidos": "Flores",
    "materias": ["Matemáticas", "Ciencias Naturales", "Lengua y Literatura", "Educación Física", "Historia de Venezuela"],
    "seccion": "B",
    "año": "1er Año",
    "genero": "Femenino",
    "estado": "Activo",
    "direccion": "Avenida Bolívar, Centro Comercial Plaza, Local 10",
    "email": "isabella.flores@example.com",
    "asistencias": { "matemáticas": 36, "ciencias_naturales": 37, "lengua_y_literatura": 35, "educación_física": 37, "historia_de_venezuela": 36 },
    "notas": { "matemáticas": 19, "ciencias_naturales": 18, "lengua_y_literatura": 15, "educación_física": 17, "historia_de_venezuela": 16 },
    "nombre_representante": "Ricardo Flores",
    "cedula_representante": "V-8567890",
    "fecha_nacimiento": "2011-03-14"
  },
  {
    "cedula": "V-26123456",
    "nombre": "Daniel",
    "apellidos": "Moreno",
    "materias": ["Matemáticas", "Ciencias Naturales", "Lengua y Literatura", "Educación Física", "Geografía de Venezuela"],
    "seccion": "C",
    "año": "1er Año",
    "genero": "Masculino",
    "estado": "Activo",
    "direccion": "Urbanización Las Acacias, Calle 1, Casa 9",
    "email": "daniel.moreno@example.com",
    "asistencias": { "matemáticas": 36, "ciencias_naturales": 37, "lengua_y_literatura": 38, "educación_física": 36, "geografía_de_venezuela": 37 },
    "notas": { "matemáticas": 14, "ciencias_naturales": 17, "lengua_y_literatura": 18, "educación_física": 16, "geografía_de_venezuela": 19 },
    "nombre_representante": "Beatriz Moreno",
    "cedula_representante": "V-7123456",
    "fecha_nacimiento": "2011-06-28"
  },
  {
    "cedula": "V-26234567",
    "nombre": "Camila",
    "apellidos": "Jiménez",
    "materias": ["Matemáticas", "Ciencias Naturales", "Lengua y Literatura", "Educación Física", "Geografía de Venezuela"],
    "seccion": "C",
    "año": "1er Año",
    "genero": "Femenino",
    "estado": "Activo",
    "direccion": "Residencias El Parque, Torre B, Apto 5-C",
    "email": "camila.jimenez@example.com",
    "asistencias": { "matemáticas": 38, "ciencias_naturales": 37, "lengua_y_literatura": 38, "educación_física": 37, "geografía_de_venezuela": 39 },
    "notas": { "matemáticas": 18, "ciencias_naturales": 16, "lengua_y_literatura": 17, "educación_física": 15, "geografía_de_venezuela": 20 },
    "nombre_representante": "Roberto Jiménez",
    "cedula_representante": "V-7234567",
    "fecha_nacimiento": "2011-09-01"
  },
  {
    "cedula": "V-26345678",
    "nombre": "Jorge",
    "apellidos": "Ruiz",
    "materias": ["Matemáticas", "Ciencias Naturales", "Lengua y Literatura", "Educación Física", "Geografía de Venezuela"],
    "seccion": "C",
    "año": "1er Año",
    "genero": "Masculino",
    "estado": "Activo",
    "direccion": "Calle Principal, Casa #12, Barrio Obrero",
    "email": "jorge.ruiz@example.com",
    "asistencias": { "matemáticas": 35, "ciencias_naturales": 36, "lengua_y_literatura": 35, "educación_física": 36, "geografía_de_venezuela": 35 },
    "notas": { "matemáticas": 16, "ciencias_naturales": 19, "lengua_y_literatura": 15, "educación_física": 18, "geografía_de_venezuela": 17 },
    "nombre_representante": "Patricia Ruiz",
    "cedula_representante": "V-7345678",
    "fecha_nacimiento": "2011-12-15"
  },
  {
    "cedula": "V-26456789",
    "nombre": "Lucía",
    "apellidos": "Castillo",
    "materias": ["Matemáticas", "Ciencias Naturales", "Lengua y Literatura", "Educación Física", "Geografía de Venezuela"],
    "seccion": "C",
    "año": "1er Año",
    "genero": "Femenino",
    "estado": "Activo",
    "direccion": "Avenida 19 de Abril, Edificio Torbes, Piso 1",
    "email": "lucia.castillo@example.com",
    "asistencias": { "matemáticas": 37, "ciencias_naturales": 36, "lengua_y_literatura": 38, "educación_física": 37, "geografía_de_venezuela": 38 },
    "notas": { "matemáticas": 17, "ciencias_naturales": 15, "lengua_y_literatura": 19, "educación_física": 16, "geografía_de_venezuela": 18 },
    "nombre_representante": "Francisco Castillo",
    "cedula_representante": "V-7456789",
    "fecha_nacimiento": "2011-02-28"
  },
  {
    "cedula": "V-26567890",
    "nombre": "Mateo",
    "apellidos": "Romero",
    "materias": ["Matemáticas", "Ciencias Naturales", "Lengua y Literatura", "Educación Física", "Geografía de Venezuela"],
    "seccion": "C",
    "año": "1er Año",
    "genero": "Masculino",
    "estado": "Activo",
    "direccion": "Urbanización Santa Rosa, Calle 3, #11-22",
    "email": "mateo.romero@example.com",
    "asistencias": { "matemáticas": 36, "ciencias_naturales": 37, "lengua_y_literatura": 36, "educación_física": 35, "geografía_de_venezuela": 36 },
    "notas": { "matemáticas": 15, "ciencias_naturales": 18, "lengua_y_literatura": 16, "educación_física": 17, "geografía_de_venezuela": 19 },
    "nombre_representante": "Verónica Romero",
    "cedula_representante": "V-7567890",
    "fecha_nacimiento": "2011-05-13"
  },
  // --- 2do Año ---
  {
    "cedula": "V-25123456",
    "nombre": "Valeria",
    "apellidos": "Peña",
    "materias": ["Matemáticas", "Biología", "Química", "Castellano", "Inglés"],
    "seccion": "A",
    "año": "2do Año",
    "genero": "Femenino",
    "estado": "Activo",
    "direccion": "Avenida España, Conjunto Residencial La Colina",
    "email": "valeria.pena@example.com",
    "asistencias": { "matemáticas": 39, "biología": 40, "química": 38, "castellano": 39, "inglés": 39 },
    "notas": { "matemáticas": 16, "biología": 18, "química": 17, "castellano": 15, "inglés": 19 },
    "nombre_representante": "Daniel Peña",
    "cedula_representante": "V-10123456",
    "fecha_nacimiento": "2010-08-17"
  },
  {
    "cedula": "V-25234567",
    "nombre": "Adrián",
    "apellidos": "Mendoza",
    "materias": ["Matemáticas", "Biología", "Química", "Castellano", "Inglés"],
    "seccion": "A",
    "año": "2do Año",
    "genero": "Masculino",
    "estado": "Activo",
    "direccion": "Calle Los Pinos, Edificio Roble, Apto 6-A",
    "email": "adrian.mendoza@example.com",
    "asistencias": { "matemáticas": 38, "biología": 39, "química": 37, "castellano": 38, "inglés": 40 },
    "notas": { "matemáticas": 18, "biología": 16, "química": 15, "castellano": 17, "inglés": 20 },
    "nombre_representante": "Adriana Mendoza",
    "cedula_representante": "V-10234567",
    "fecha_nacimiento": "2010-11-21"
  },
  {
    "cedula": "V-25345678",
    "nombre": "Paula",
    "apellidos": "Herrera",
    "materias": ["Matemáticas", "Biología", "Química", "Castellano", "Inglés"],
    "seccion": "A",
    "año": "2do Año",
    "genero": "Femenino",
    "estado": "Activo",
    "direccion": "Urbanización El Trigal, Calle Principal, Casa 50",
    "email": "paula.herrera@example.com",
    "asistencias": { "matemáticas": 37, "biología": 38, "química": 36, "castellano": 38, "inglés": 39 },
    "notas": { "matemáticas": 17, "biología": 19, "química": 16, "castellano": 18, "inglés": 17 },
    "nombre_representante": "Rafael Herrera",
    "cedula_representante": "V-10345678",
    "fecha_nacimiento": "2010-01-04"
  },
  {
    "cedula": "V-25456789",
    "nombre": "Javier",
    "apellidos": "Vargas",
    "materias": ["Matemáticas", "Biología", "Química", "Castellano", "Inglés"],
    "seccion": "A",
    "año": "2do Año",
    "genero": "Masculino",
    "estado": "Activo",
    "direccion": "Avenida Intercomunal, Sector La Mora, Edif. 7",
    "email": "javier.vargas@example.com",
    "asistencias": { "matemáticas": 39, "biología": 40, "química": 39, "castellano": 40, "inglés": 40 },
    "notas": { "matemáticas": 15, "biología": 17, "química": 18, "castellano": 19, "inglés": 16 },
    "nombre_representante": "Mónica Vargas",
    "cedula_representante": "V-10456789",
    "fecha_nacimiento": "2010-04-09"
  },
  {
    "cedula": "V-25567890",
    "nombre": "Mariana",
    "apellidos": "Mora",
    "materias": ["Matemáticas", "Biología", "Química", "Castellano", "Inglés"],
    "seccion": "A",
    "año": "2do Año",
    "genero": "Femenino",
    "estado": "Activo",
    "direccion": "Carretera Panamericana, Km 15, Finca El Rosal",
    "email": "mariana.mora@example.com",
    "asistencias": { "matemáticas": 38, "biología": 37, "química": 39, "castellano": 38, "inglés": 39 },
    "notas": { "matemáticas": 19, "biología": 15, "química": 17, "castellano": 16, "inglés": 18 },
    "nombre_representante": "Oscar Mora",
    "cedula_representante": "V-10567890",
    "fecha_nacimiento": "2010-07-13"
  },
  {
    "cedula": "V-24123456",
    "nombre": "Felipe",
    "apellidos": "Medina",
    "materias": ["Matemáticas", "Biología", "Física", "Castellano", "Geografía General"],
    "seccion": "B",
    "año": "2do Año",
    "genero": "Masculino",
    "estado": "Activo",
    "direccion": "Barrio Sucre, Calle 2, Casa #33-A",
    "email": "felipe.medina@example.com",
    "asistencias": { "matemáticas": 38, "biología": 39, "física": 38, "castellano": 39, "geografía_general": 39 },
    "notas": { "matemáticas": 17, "biología": 16, "física": 18, "castellano": 15, "geografía_general": 19 },
    "nombre_representante": "Luisa Medina",
    "cedula_representante": "V-11123456",
    "fecha_nacimiento": "2010-10-26"
  },
  {
    "cedula": "V-24234567",
    "nombre": "Sara",
    "apellidos": "Rivas",
    "materias": ["Matemáticas", "Biología", "Física", "Castellano", "Geografía General"],
    "seccion": "B",
    "año": "2do Año",
    "genero": "Femenino",
    "estado": "Activo",
    "direccion": "Avenida Rotaria, Edificio San Miguel, Apto 2-D",
    "email": "sara.rivas@example.com",
    "asistencias": { "matemáticas": 39, "biología": 39, "física": 38, "castellano": 40, "geografía_general": 40 },
    "notas": { "matemáticas": 16, "biología": 17, "física": 15, "castellano": 19, "geografía_general": 18 },
    "nombre_representante": "Julio Rivas",
    "cedula_representante": "V-11234567",
    "fecha_nacimiento": "2010-12-08"
  },
  {
    "cedula": "V-24345678",
    "nombre": "Marcos",
    "apellidos": "Lugo",
    "materias": ["Matemáticas", "Biología", "Física", "Castellano", "Geografía General"],
    "seccion": "B",
    "año": "2do Año",
    "genero": "Masculino",
    "estado": "Activo",
    "direccion": "Urbanización La Concordia, Calle 12, Casa 1-45",
    "email": "marcos.lugo@example.com",
    "asistencias": { "matemáticas": 38, "biología": 38, "física": 37, "castellano": 38, "geografía_general": 38 },
    "notas": { "matemáticas": 19, "biología": 18, "física": 16, "castellano": 17, "geografía_general": 15 },
    "nombre_representante": "Elena Lugo",
    "cedula_representante": "V-11345678",
    "fecha_nacimiento": "2010-03-03"
  },
  {
    "cedula": "V-24456789",
    "nombre": "Elena",
    "apellidos": "Castro",
    "materias": ["Matemáticas", "Biología", "Física", "Castellano", "Geografía General"],
    "seccion": "B",
    "año": "2do Año",
    "genero": "Femenino",
    "estado": "Activo",
    "direccion": "Avenida Los Agustinos, Quinta Doña Carmen",
    "email": "elena.castro@example.com",
    "asistencias": { "matemáticas": 40, "biología": 39, "física": 40, "castellano": 40, "geografía_general": 40 },
    "notas": { "matemáticas": 18, "biología": 15, "física": 17, "castellano": 16, "geografía_general": 20 },
    "nombre_representante": "Alfredo Castro",
    "cedula_representante": "V-11456789",
    "fecha_nacimiento": "2010-06-07"
  },
  {
    "cedula": "V-24567890",
    "nombre": "Ricardo",
    "apellidos": "Silva",
    "materias": ["Matemáticas", "Biología", "Física", "Castellano", "Geografía General"],
    "seccion": "B",
    "año": "2do Año",
    "genero": "Masculino",
    "estado": "Activo",
    "direccion": "Residencias Don Bosco, Torre A, Apto 8-B",
    "email": "ricardo.silva@example.com",
    "asistencias": { "matemáticas": 38, "biología": 38, "física": 38, "castellano": 38, "geografía_general": 38 },
    "notas": { "matemáticas": 15, "biología": 19, "física": 18, "castellano": 17, "geografía_general": 16 },
    "nombre_representante": "Carolina Silva",
    "cedula_representante": "V-11567890",
    "fecha_nacimiento": "2010-09-11"
  },
  {
    "cedula": "V-23123456",
    "nombre": "Andrea",
    "apellidos": "Acosta",
    "materias": ["Matemáticas", "Química", "Física", "Historia Universal", "Inglés"],
    "seccion": "C",
    "año": "2do Año",
    "genero": "Femenino",
    "estado": "Activo",
    "direccion": "Calle Principal, Edif. San Judas, Piso 3",
    "email": "andrea.acosta@example.com",
    "asistencias": { "matemáticas": 39, "química": 38, "física": 39, "historia_universal": 39, "inglés": 39 },
    "notas": { "matemáticas": 17, "química": 18, "física": 16, "historia_universal": 19, "inglés": 15 },
    "nombre_representante": "Héctor Acosta",
    "cedula_representante": "V-12123456",
    "fecha_nacimiento": "2010-11-15"
  },
  {
    "cedula": "V-23234567",
    "nombre": "David",
    "apellidos": "Rios",
    "materias": ["Matemáticas", "Química", "Física", "Historia Universal", "Inglés"],
    "seccion": "C",
    "año": "2do Año",
    "genero": "Masculino",
    "estado": "Activo",
    "direccion": "Avenida Las Américas, Res. Orinoco, Apto 10-A",
    "email": "david.rios@example.com",
    "asistencias": { "matemáticas": 39, "química": 40, "física": 39, "historia_universal": 39, "inglés": 40 },
    "notas": { "matemáticas": 16, "química": 17, "física": 19, "historia_universal": 15, "inglés": 18 },
    "nombre_representante": "Diana Rios",
    "cedula_representante": "V-12234567",
    "fecha_nacimiento": "2010-02-19"
  },
  {
    "cedula": "V-23345678",
    "nombre": "Natalia",
    "apellidos": "Salazar",
    "materias": ["Matemáticas", "Química", "Física", "Historia Universal", "Inglés"],
    "seccion": "C",
    "año": "2do Año",
    "genero": "Femenino",
    "estado": "Activo",
    "direccion": "Urbanización La Arboleda, Calle Las Flores, #22",
    "email": "natalia.salazar@example.com",
    "asistencias": { "matemáticas": 37, "química": 38, "física": 37, "historia_universal": 38, "inglés": 37 },
    "notas": { "matemáticas": 18, "química": 15, "física": 17, "historia_universal": 20, "inglés": 16 },
    "nombre_representante": "Eduardo Salazar",
    "cedula_representante": "V-12345678",
    "fecha_nacimiento": "2010-05-24"
  },
  {
    "cedula": "V-23456789",
    "nombre": "José",
    "apellidos": "Guzmán",
    "materias": ["Matemáticas", "Química", "Física", "Historia Universal", "Inglés"],
    "seccion": "C",
    "año": "2do Año",
    "genero": "Masculino",
    "estado": "Activo",
    "direccion": "Barrio El Carmen, Vereda 5, Casa #3",
    "email": "jose.guzman@example.com",
    "asistencias": { "matemáticas": 40, "química": 40, "física": 40, "historia_universal": 40, "inglés": 40 },
    "notas": { "matemáticas": 19, "química": 16, "física": 18, "historia_universal": 17, "inglés": 15 },
    "nombre_representante": "Lorena Guzmán",
    "cedula_representante": "V-12456789",
    "fecha_nacimiento": "2010-08-28"
  },
  {
    "cedula": "V-23567890",
    "nombre": "Victoria",
    "apellidos": "Rojas",
    "materias": ["Matemáticas", "Química", "Física", "Historia Universal", "Inglés"],
    "seccion": "C",
    "año": "2do Año",
    "genero": "Femenino",
    "estado": "Activo",
    "direccion": "Avenida Principal de Pueblo Nuevo, Edif. Roraima",
    "email": "victoria.rojas@example.com",
    "asistencias": { "matemáticas": 37, "química": 37, "física": 37, "historia_universal": 37, "inglés": 37 },
    "notas": { "matemáticas": 15, "química": 19, "física": 16, "historia_universal": 18, "inglés": 17 },
    "nombre_representante": "Gustavo Rojas",
    "cedula_representante": "V-12567890",
    "fecha_nacimiento": "2010-10-01"
  },
  // --- 3er Año ---
  {
    "cedula": "V-22123456",
    "nombre": "Alejandro",
    "apellidos": "Bravo",
    "materias": ["Matemáticas", "Física", "Química", "Biología", "Castellano"],
    "seccion": "A",
    "año": "3er Año",
    "genero": "Masculino",
    "estado": "Activo",
    "direccion": "Calle 14, entre Carreras 20 y 21, Casa #20-5",
    "email": "alejandro.bravo@example.com",
    "asistencias": { "matemáticas": 42, "física": 42, "química": 41, "biología": 43, "castellano": 42 },
    "notas": { "matemáticas": 18, "física": 17, "química": 16, "biología": 19, "castellano": 15 },
    "nombre_representante": "Raquel Bravo",
    "cedula_representante": "V-13123456",
    "fecha_nacimiento": "2009-01-05"
  },
  {
    "cedula": "V-22234567",
    "nombre": "Fernanda",
    "apellidos": "Luna",
    "materias": ["Matemáticas", "Física", "Química", "Biología", "Castellano"],
    "seccion": "A",
    "año": "3er Año",
    "genero": "Femenino",
    "estado": "Activo",
    "direccion": "Avenida Las Ferias, Edificio La Giralda, Piso 5",
    "email": "fernanda.luna@example.com",
    "asistencias": { "matemáticas": 41, "física": 41, "química": 40, "biología": 42, "castellano": 41 },
    "notas": { "matemáticas": 16, "física": 18, "química": 15, "biología": 17, "castellano": 20 },
    "nombre_representante": "Simón Luna",
    "cedula_representante": "V-13234567",
    "fecha_nacimiento": "2009-04-10"
  },
  {
    "cedula": "V-22345678",
    "nombre": "Sebastián",
    "apellidos": "Reyes",
    "materias": ["Matemáticas", "Física", "Química", "Biología", "Castellano"],
    "seccion": "A",
    "año": "3er Año",
    "genero": "Masculino",
    "estado": "Activo",
    "direccion": "Urbanización Prebo, Vereda 8, Casa #14",
    "email": "sebastian.reyes@example.com",
    "asistencias": { "matemáticas": 43, "física": 43, "química": 42, "biología": 44, "castellano": 43 },
    "notas": { "matemáticas": 17, "física": 15, "química": 19, "biología": 16, "castellano": 18 },
    "nombre_representante": "Teresa Reyes",
    "cedula_representante": "V-13345678",
    "fecha_nacimiento": "2009-07-15"
  },
  {
    "cedula": "V-22456789",
    "nombre": "Antonia",
    "apellidos": "Figueroa",
    "materias": ["Matemáticas", "Física", "Química", "Biología", "Castellano"],
    "seccion": "A",
    "año": "3er Año",
    "genero": "Femenino",
    "estado": "Activo",
    "direccion": "Avenida Lara, C.C. Metrópolis, Nivel 2",
    "email": "antonia.figueroa@example.com",
    "asistencias": { "matemáticas": 42, "física": 41, "química": 42, "biología": 42, "castellano": 41 },
    "notas": { "matemáticas": 19, "física": 16, "química": 17, "biología": 18, "castellano": 15 },
    "nombre_representante": "Armando Figueroa",
    "cedula_representante": "V-13456789",
    "fecha_nacimiento": "2009-10-20"
  },
  {
    "cedula": "V-22567890",
    "nombre": "Manuel",
    "apellidos": "Aponte",
    "materias": ["Matemáticas", "Física", "Química", "Biología", "Castellano"],
    "seccion": "A",
    "año": "3er Año",
    "genero": "Masculino",
    "estado": "Activo",
    "direccion": "Sector La Machiri, Calle Los Robles, #5-55",
    "email": "manuel.aponte@example.com",
    "asistencias": { "matemáticas": 42, "física": 43, "química": 42, "biología": 43, "castellano": 42 },
    "notas": { "matemáticas": 15, "física": 19, "química": 18, "biología": 16, "castellano": 17 },
    "nombre_representante": "Susana Aponte",
    "cedula_representante": "V-13567890",
    "fecha_nacimiento": "2009-12-25"
  },
  {
    "cedula": "V-21123456",
    "nombre": "Renata",
    "apellidos": "Gil",
    "materias": ["Matemáticas", "Física", "Química", "Inglés", "Historia Contemporánea de Venezuela"],
    "seccion": "B",
    "año": "3er Año",
    "genero": "Femenino",
    "estado": "Activo",
    "direccion": "Avenida Ferrero Tamayo, Edif. Pirineos, Piso 1",
    "email": "renata.gil@example.com",
    "asistencias": { "matemáticas": 41, "física": 42, "química": 41, "inglés": 42, "historia_contemporánea_de_venezuela": 41 },
    "notas": { "matemáticas": 17, "física": 16, "química": 19, "inglés": 18, "historia_contemporánea_de_venezuela": 15 },
    "nombre_representante": "Diego Gil",
    "cedula_representante": "V-14123456",
    "fecha_nacimiento": "2009-03-01"
  },
  {
    "cedula": "V-21234567",
    "nombre": "Lucas",
    "apellidos": "Campos",
    "materias": ["Matemáticas", "Física", "Química", "Inglés", "Historia Contemporánea de Venezuela"],
    "seccion": "B",
    "año": "3er Año",
    "genero": "Masculino",
    "estado": "Activo",
    "direccion": "Barrio San José, Calle El Río, Casa #90",
    "email": "lucas.campos@example.com",
    "asistencias": { "matemáticas": 42, "física": 42, "química": 42, "inglés": 42, "historia_contemporánea_de_venezuela": 43 },
    "notas": { "matemáticas": 16, "física": 17, "química": 18, "inglés": 15, "historia_contemporánea_de_venezuela": 19 },
    "nombre_representante": "Fabiola Campos",
    "cedula_representante": "V-14234567",
    "fecha_nacimiento": "2009-06-05"
  },
  {
    "cedula": "V-21345678",
    "nombre": "Julieta",
    "apellidos": "Soto",
    "materias": ["Matemáticas", "Física", "Química", "Inglés", "Historia Contemporánea de Venezuela"],
    "seccion": "B",
    "año": "3er Año",
    "genero": "Femenino",
    "estado": "Activo",
    "direccion": "Final Avenida 23 de Enero, Conjunto Residencial Paramillo",
    "email": "julieta.soto@example.com",
    "asistencias": { "matemáticas": 41, "física": 40, "química": 41, "inglés": 41, "historia_contemporánea_de_venezuela": 41 },
    "notas": { "matemáticas": 19, "física": 15, "química": 16, "inglés": 20, "historia_contempornea_áde_venezuela": 17 },
    "nombre_representante": "Nelson Soto",
    "cedula_representante": "V-14345678",
    "fecha_nacimiento": "2009-09-09"
  },
  {
    "cedula": "V-21456789",
    "nombre": "Emiliano",
    "apellidos": "Ponce",
    "materias": ["Matemáticas", "Física", "Química", "Inglés", "Historia Contemporánea de Venezuela"],
    "seccion": "B",
    "año": "3er Año",
    "genero": "Masculino",
    "estado": "Activo",
    "direccion": "Urbanización Santa Teresa, Calle 8, #12-A",
    "email": "emiliano.ponce@example.com",
    "asistencias": { "matemáticas": 43, "física": 43, "química": 42, "inglés": 43, "historia_contemporánea_de_venezuela": 43 },
    "notas": { "matemáticas": 18, "física": 19, "química": 15, "inglés": 17, "historia_contemporánea_de_venezuela": 16 },
    "nombre_representante": "Gloria Ponce",
    "cedula_representante": "V-14456789",
    "fecha_nacimiento": "2009-12-13"
  },
  {
    "cedula": "V-21567890",
    "nombre": "Abril",
    "apellidos": "Vega",
    "materias": ["Matemáticas", "Física", "Química", "Inglés", "Historia Contemporánea de Venezuela"],
    "seccion": "B",
    "año": "3er Año",
    "genero": "Femenino",
    "estado": "Activo",
    "direccion": "Avenida Carabobo, Edificio El Dorado, Piso 7",
    "email": "abril.vega@example.com",
    "asistencias": { "matemáticas": 41, "física": 41, "química": 41, "inglés": 42, "historia_contemporánea_de_venezuela": 41 },
    "notas": { "matemáticas": 15, "física": 18, "química": 17, "inglés": 16, "historia_contemporánea_de_venezuela": 19 },
    "nombre_representante": "Elias Vega",
    "cedula_representante": "V-14567890",
    "fecha_nacimiento": "2009-02-17"
  },
  {
    "cedula": "V-20123456",
    "nombre": "Thiago",
    "apellidos": "Solano",
    "materias": ["Matemáticas", "Física", "Química", "Educación Artística", "Formación Familiar y Ciudadana"],
    "seccion": "C",
    "año": "3er Año",
    "genero": "Masculino",
    "estado": "Activo",
    "direccion": "Calle Los Próceres, Quinta Santa Ana",
    "email": "thiago.solano@example.com",
    "asistencias": { "matemáticas": 42, "física": 42, "química": 41, "educación_artística": 42, "formación_familiar_y_ciudadana": 42 },
    "notas": { "matemáticas": 16, "física": 19, "química": 18, "educación_artística": 17, "formación_familiar_y_ciudadana": 15 },
    "nombre_representante": "Lilian Solano",
    "cedula_representante": "V-15123456",
    "fecha_nacimiento": "2009-05-22"
  },
  {
    "cedula": "V-20234567",
    "nombre": "Regina",
    "apellidos": "Navarro",
    "materias": ["Matemáticas", "Física", "Química", "Educación Artística", "Formación Familiar y Ciudadana"],
    "seccion": "C",
    "año": "3er Año",
    "genero": "Femenino",
    "estado": "Activo",
    "direccion": "Avenida Marginal del Torbes, Casa #200",
    "email": "regina.navarro@example.com",
    "asistencias": { "matemáticas": 41, "física": 40, "química": 41, "educación_artística": 41, "formación_familiar_y_ciudadana": 40 },
    "notas": { "matemáticas": 18, "física": 17, "química": 15, "educación_artística": 16, "formación_familiar_y_ciudadana": 20 },
    "nombre_representante": "Rodrigo Navarro",
    "cedula_representante": "V-15234567",
    "fecha_nacimiento": "2009-08-26"
  },
  {
    "cedula": "V-20345678",
    "nombre": "Iker",
    "apellidos": "Paredes",
    "materias": ["Matemáticas", "Física", "Química", "Educación Artística", "Formación Familiar y Ciudadana"],
    "seccion": "C",
    "año": "3er Año",
    "genero": "Masculino",
    "estado": "Activo",
    "direccion": "Urbanización Las Vegas, Manzana 3, Casa 1",
    "email": "iker.paredes@example.com",
    "asistencias": { "matemáticas": 43, "física": 42, "química": 43, "educación_artística": 43, "formación_familiar_y_ciudadana": 42 },
    "notas": { "matemáticas": 15, "física": 16, "química": 17, "educación_artística": 19, "formación_familiar_y_ciudadana": 18 },
    "nombre_representante": "Esther Paredes",
    "cedula_representante": "V-15345678",
    "fecha_nacimiento": "2009-11-30"
  },
  {
    "cedula": "V-20456789",
    "nombre": "Mia",
    "apellidos": "Arias",
    "materias": ["Matemáticas", "Física", "Química", "Educación Artística", "Formación Familiar y Ciudadana"],
    "seccion": "C",
    "año": "3er Año",
    "genero": "Femenino",
    "estado": "Activo",
    "direccion": "Barrio La Ermita, Calle Principal, #14-2",
    "email": "mia.arias@example.com",
    "asistencias": { "matemáticas": 40, "física": 41, "química": 40, "educación_artística": 41, "formación_familiar_y_ciudadana": 40 },
    "notas": { "matemáticas": 19, "física": 18, "química": 16, "educación_artística": 15, "formación_familiar_y_ciudadana": 17 },
    "nombre_representante": "César Arias",
    "cedula_representante": "V-15456789",
    "fecha_nacimiento": "2009-01-23"
  },
  {
    "cedula": "V-20567890",
    "nombre": "Leonardo",
    "apellidos": "Cordero",
    "materias": ["Matemáticas", "Física", "Química", "Educación Artística", "Formación Familiar y Ciudadana"],
    "seccion": "C",
    "año": "3er Año",
    "genero": "Masculino",
    "estado": "Activo",
    "direccion": "Avenida 1, Edificio Los Andes, Apto 9-C",
    "email": "leonardo.cordero@example.com",
    "asistencias": { "matemáticas": 43, "física": 43, "química": 43, "educación_artística": 44, "formación_familiar_y_ciudadana": 43 },
    "notas": { "matemáticas": 17, "física": 15, "química": 19, "educación_artística": 18, "formación_familiar_y_ciudadana": 16 },
    "nombre_representante": "Rosa Cordero",
    "cedula_representante": "V-15567890",
    "fecha_nacimiento": "2009-04-28"
  },
  // --- 4to Año ---
  {
    "cedula": "V-19123456",
    "nombre": "Liliana",
    "apellidos": "Urbina",
    "materias": ["Matemáticas", "Física", "Química", "Castellano", "Ciencias de la Tierra"],
    "seccion": "A",
    "año": "4to Año",
    "genero": "Femenino",
    "estado": "Activo",
    "direccion": "Urbanización Pirineos, Calle Los Cerezos, #18",
    "email": "liliana.urbina@example.com",
    "asistencias": { "matemáticas": 44, "física": 44, "química": 43, "castellano": 45, "ciencias_de_la_tierra": 44 },
    "notas": { "matemáticas": 15, "física": 18, "química": 17, "castellano": 16, "ciencias_de_la_tierra": 19 },
    "nombre_representante": "Jesús Urbina",
    "cedula_representante": "V-16123456",
    "fecha_nacimiento": "2008-07-02"
  },
  {
    "cedula": "V-19234567",
    "nombre": "Maximiliano",
    "apellidos": "Meza",
    "materias": ["Matemáticas", "Física", "Química", "Castellano", "Ciencias de la Tierra"],
    "seccion": "A",
    "año": "4to Año",
    "genero": "Masculino",
    "estado": "Activo",
    "direccion": "Avenida Rotaria, Edificio Tamanaco, Apto 1-A",
    "email": "maximiliano.meza@example.com",
    "asistencias": { "matemáticas": 45, "física": 45, "química": 44, "castellano": 46, "ciencias_de_la_tierra": 45 },
    "notas": { "matemáticas": 18, "física": 15, "química": 16, "castellano": 19, "ciencias_de_la_tierra": 17 },
    "nombre_representante": "Iris Meza",
    "cedula_representante": "V-16234567",
    "fecha_nacimiento": "2008-10-06"
  },
  {
    "cedula": "V-19345678",
    "nombre": "Ximena",
    "apellidos": "Blanco",
    "materias": ["Matemáticas", "Física", "Química", "Castellano", "Ciencias de la Tierra"],
    "seccion": "A",
    "año": "4to Año",
    "genero": "Femenino",
    "estado": "Activo",
    "direccion": "Calle Ancha, Casa #30, La Concordia",
    "email": "ximena.blanco@example.com",
    "asistencias": { "matemáticas": 43, "física": 44, "química": 43, "castellano": 44, "ciencias_de_la_tierra": 44 },
    "notas": { "matemáticas": 17, "física": 16, "química": 19, "castellano": 15, "ciencias_de_la_tierra": 18 },
    "nombre_representante": "Omar Blanco",
    "cedula_representante": "V-16345678",
    "fecha_nacimiento": "2008-01-10"
  },
  {
    "cedula": "V-19456789",
    "nombre": "Bruno",
    "apellidos": "Molina",
    "materias": ["Matemáticas", "Física", "Química", "Castellano", "Ciencias de la Tierra"],
    "seccion": "A",
    "año": "4to Año",
    "genero": "Masculino",
    "estado": "Activo",
    "direccion": "Avenida Principal, Edif. Bella Vista, Piso 8",
    "email": "bruno.molina@example.com",
    "asistencias": { "matemáticas": 44, "física": 45, "química": 44, "castellano": 45, "ciencias_de_la_tierra": 44 },
    "notas": { "matemáticas": 16, "física": 19, "química": 15, "castellano": 18, "ciencias_de_la_tierra": 20 },
    "nombre_representante": "Elsa Molina",
    "cedula_representante": "V-16456789",
    "fecha_nacimiento": "2008-04-15"
  },
  {
    "cedula": "V-19567890",
    "nombre": "Aitana",
    "apellidos": "Sosa",
    "materias": ["Matemáticas", "Física", "Química", "Castellano", "Ciencias de la Tierra"],
    "seccion": "A",
    "año": "4to Año",
    "genero": "Femenino",
    "estado": "Activo",
    "direccion": "Urbanización El Prado, Calle Las Flores, #10",
    "email": "aitana.sosa@example.com",
    "asistencias": { "matemáticas": 46, "física": 45, "química": 46, "castellano": 46, "ciencias_de_la_tierra": 45 },
    "notas": { "matemáticas": 19, "física": 17, "química": 18, "castellano": 16, "ciencias_de_la_tierra": 15 },
    "nombre_representante": "Hugo Sosa",
    "cedula_representante": "V-16567890",
    "fecha_nacimiento": "2008-07-20"
  },
  {
    "cedula": "V-18123456",
    "nombre": "Gael",
    "apellidos": "Ortega",
    "materias": ["Matemáticas", "Física", "Química", "Biología", "Premilitar"],
    "seccion": "B",
    "año": "4to Año",
    "genero": "Masculino",
    "estado": "Activo",
    "direccion": "Residencias El Carmen, Torre C, Apto 2-B",
    "email": "gael.ortega@example.com",
    "asistencias": { "matemáticas": 44, "física": 45, "química": 44, "biología": 45, "premilitar": 45 },
    "notas": { "matemáticas": 15, "física": 17, "química": 16, "biología": 18, "premilitar": 20 },
    "nombre_representante": "Eva Ortega",
    "cedula_representante": "V-17123456",
    "fecha_nacimiento": "2008-10-24"
  },
  {
    "cedula": "V-18234567",
    "nombre": "Catalina",
    "apellidos": "Delgado",
    "materias": ["Matemáticas", "Física", "Química", "Biología", "Premilitar"],
    "seccion": "B",
    "año": "4to Año",
    "genero": "Femenino",
    "estado": "Activo",
    "direccion": "Avenida Las Pilas, Quinta San Antonio",
    "email": "catalina.delgado@example.com",
    "asistencias": { "matemáticas": 45, "física": 46, "química": 45, "biología": 46, "premilitar": 45 },
    "notas": { "matemáticas": 17, "física": 15, "química": 18, "biología": 16, "premilitar": 19 },
    "nombre_representante": "Abel Delgado",
    "cedula_representante": "V-17234567",
    "fecha_nacimiento": "2008-01-28"
  },
  {
    "cedula": "V-18345678",
    "nombre": "Dante",
    "apellidos": "Marin",
    "materias": ["Matemáticas", "Física", "Química", "Biología", "Premilitar"],
    "seccion": "B",
    "año": "4to Año",
    "genero": "Masculino",
    "estado": "Activo",
    "direccion": "Barrio Guzmán Blanco, Calle 3, #15",
    "email": "dante.marin@example.com",
    "asistencias": { "matemáticas": 44, "física": 43, "química": 44, "biología": 44, "premilitar": 44 },
    "notas": { "matemáticas": 16, "física": 18, "química": 19, "biología": 15, "premilitar": 17 },
    "nombre_representante": "Silvia Marin",
    "cedula_representante": "V-17345678",
    "fecha_nacimiento": "2008-05-03"
  },
  {
    "cedula": "V-18456789",
    "nombre": "Amanda",
    "apellidos": "Nuñez",
    "materias": ["Matemáticas", "Física", "Química", "Biología", "Premilitar"],
    "seccion": "B",
    "año": "4to Año",
    "genero": "Femenino",
    "estado": "Activo",
    "direccion": "Urbanización Los Naranjos, Av. Principal, #77",
    "email": "amanda.nunez@example.com",
    "asistencias": { "matemáticas": 46, "física": 45, "química": 46, "biología": 46, "premilitar": 46 },
    "notas": { "matemáticas": 18, "física": 16, "química": 17, "biología": 19, "premilitar": 15 },
    "nombre_representante": "Raúl Nuñez",
    "cedula_representante": "V-17456789",
    "fecha_nacimiento": "2008-08-07"
  },
  {
    "cedula": "V-18567890",
    "nombre": "Fabian",
    "apellidos": "Parra",
    "materias": ["Matemáticas", "Física", "Química", "Biología", "Premilitar"],
    "seccion": "B",
    "año": "4to Año",
    "genero": "Masculino",
    "estado": "Activo",
    "direccion": "Edificio Don Pepe, Apto 1-B, Centro",
    "email": "fabian.parra@example.com",
    "asistencias": { "matemáticas": 44, "física": 44, "química": 44, "biología": 45, "premilitar": 44 },
    "notas": { "matemáticas": 19, "física": 17, "química": 15, "biología": 18, "premilitar": 16 },
    "nombre_representante": "Clara Parra",
    "cedula_representante": "V-17567890",
    "fecha_nacimiento": "2008-11-11"
  },
  {
    "cedula": "V-17123456",
    "nombre": "Olivia",
    "apellidos": "Leon",
    "materias": ["Matemáticas", "Física", "Química", "Dibujo Técnico", "Psicología"],
    "seccion": "C",
    "año": "4to Año",
    "genero": "Femenino",
    "estado": "Activo",
    "direccion": "Avenida Lucio Oquendo, Res. El Trébol",
    "email": "olivia.leon@example.com",
    "asistencias": { "matemáticas": 45, "física": 45, "química": 45, "dibujo_técnico": 46, "psicología": 45 },
    "notas": { "matemáticas": 17, "física": 19, "química": 18, "dibujo_técnico": 16, "psicología": 15 },
    "nombre_representante": "Iván Leon",
    "cedula_representante": "V-18123456",
    "fecha_nacimiento": "2008-02-14"
  },
  {
    "cedula": "V-17234567",
    "nombre": "Hugo",
    "apellidos": "Rangel",
    "materias": ["Matemáticas", "Física", "Química", "Dibujo Técnico", "Psicología"],
    "seccion": "C",
    "año": "4to Año",
    "genero": "Masculino",
    "estado": "Activo",
    "direccion": "Calle 9, Edificio Miranda, Apto 4-A",
    "email": "hugo.rangel@example.com",
    "asistencias": { "matemáticas": 45, "física": 44, "química": 45, "dibujo_técnico": 45, "psicología": 45 },
    "notas": { "matemáticas": 16, "física": 18, "química": 17, "dibujo_técnico": 15, "psicología": 19 },
    "nombre_representante": "Noelia Rangel",
    "cedula_representante": "V-18234567",
    "fecha_nacimiento": "2008-05-19"
  },
  {
    "cedula": "V-17345678",
    "nombre": "Zoe",
    "apellidos": "Vera",
    "materias": ["Matemáticas", "Física", "Química", "Dibujo Técnico", "Psicología"],
    "seccion": "C",
    "año": "4to Año",
    "genero": "Femenino",
    "estado": "Activo",
    "direccion": "Avenida 1, Sector Las Lomas, #23-1",
    "email": "zoe.vera@example.com",
    "asistencias": { "matemáticas": 46, "física": 46, "química": 46, "dibujo_técnico": 46, "psicología": 46 },
    "notas": { "matemáticas": 18, "física": 16, "química": 15, "dibujo_técnico": 19, "psicología": 17 },
    "nombre_representante": "Félix Vera",
    "cedula_representante": "V-18345678",
    "fecha_nacimiento": "2008-08-23"
  },
  {
    "cedula": "V-17456789",
    "nombre": "Oliver",
    "apellidos": "Ibarra",
    "materias": ["Matemáticas", "Física", "Química", "Dibujo Técnico", "Psicología"],
    "seccion": "C",
    "año": "4to Año",
    "genero": "Masculino",
    "estado": "Activo",
    "direccion": "Residencias La Castellana, Torre B, Apto 6-D",
    "email": "oliver.ibarra@example.com",
    "asistencias": { "matemáticas": 43, "física": 44, "química": 43, "dibujo_técnico": 44, "psicología": 43 },
    "notas": { "matemáticas": 19, "física": 15, "química": 16, "dibujo_técnico": 17, "psicología": 18 },
    "nombre_representante": "Sara Ibarra",
    "cedula_representante": "V-18456789",
    "fecha_nacimiento": "2008-11-27"
  },
  {
    "cedula": "V-17567890",
    "nombre": "Mía",
    "apellidos": "Colmenares",
    "materias": ["Matemáticas", "Física", "Química", "Dibujo Técnico", "Psicología"],
    "seccion": "C",
    "año": "4to Año",
    "genero": "Femenino",
    "estado": "Activo",
    "direccion": "Avenida Cuatricentenaria, Edif. Los Samanes",
    "email": "mia.colmenares@example.com",
    "asistencias": { "matemáticas": 46, "física": 46, "química": 46, "dibujo_técnico": 47, "psicología": 46 },
    "notas": { "matemáticas": 15, "física": 18, "química": 17, "dibujo_técnico": 16, "psicología": 20 },
    "nombre_representante": "Leo Colmenares",
    "cedula_representante": "V-18567890",
    "fecha_nacimiento": "2008-03-02"
  },
  // --- 5to Año ---
  {
    "cedula": "V-16123456",
    "nombre": "Elias",
    "apellidos": "Velasquez",
    "materias": ["Matemáticas", "Física", "Química", "Biología", "Ciencias de la Tierra"],
    "seccion": "A",
    "año": "5to Año",
    "genero": "Masculino",
    "estado": "Activo",
    "direccion": "Urbanización La Popita, Carrera 4, #3-12",
    "email": "elias.velasquez@example.com",
    "asistencias": { "matemáticas": 48, "física": 48, "química": 47, "biología": 49, "ciencias_de_la_tierra": 48 },
    "notas": { "matemáticas": 19, "física": 18, "química": 17, "biología": 16, "ciencias_de_la_tierra": 15 },
    "nombre_representante": "Alicia Velasquez",
    "cedula_representante": "V-19123456",
    "fecha_nacimiento": "2007-06-06"
  },
  {
    "cedula": "V-16234567",
    "nombre": "Alba",
    "apellidos": "Cardenas",
    "materias": ["Matemáticas", "Física", "Química", "Biología", "Ciencias de la Tierra"],
    "seccion": "A",
    "año": "5to Año",
    "genero": "Femenino",
    "estado": "Activo",
    "direccion": "Avenida Los Próceres, Edificio Roraima, Apto 1-C",
    "email": "alba.cardenas@example.com",
    "asistencias": { "matemáticas": 47, "física": 47, "química": 46, "biología": 48, "ciencias_de_la_tierra": 47 },
    "notas": { "matemáticas": 18, "física": 17, "química": 16, "biología": 15, "ciencias_de_la_tierra": 20 },
    "nombre_representante": "Mario Cardenas",
    "cedula_representante": "V-19234567",
    "fecha_nacimiento": "2007-09-10"
  },
  {
    "cedula": "V-16345678",
    "nombre": "Mario",
    "apellidos": "Guillen",
    "materias": ["Matemáticas", "Física", "Química", "Biología", "Ciencias de la Tierra"],
    "seccion": "A",
    "año": "5to Año",
    "genero": "Masculino",
    "estado": "Activo",
    "direccion": "Calle 10, Edificio Don Bosco, Piso 2",
    "email": "mario.guillen@example.com",
    "asistencias": { "matemáticas": 49, "física": 49, "química": 48, "biología": 50, "ciencias_de_la_tierra": 49 },
    "notas": { "matemáticas": 17, "física": 16, "química": 15, "biología": 19, "ciencias_de_la_tierra": 18 },
    "nombre_representante": "Inés Guillen",
    "cedula_representante": "V-19345678",
    "fecha_nacimiento": "2007-12-15"
  },
  {
    "cedula": "V-16456789",
    "nombre": "Claudia",
    "apellidos": "Sandoval",
    "materias": ["Matemáticas", "Física", "Química", "Biología", "Ciencias de la Tierra"],
    "seccion": "A",
    "año": "5to Año",
    "genero": "Femenino",
    "estado": "Activo",
    "direccion": "Urbanización Altos de Paramillo, Manzana F, #21",
    "email": "claudia.sandoval@example.com",
    "asistencias": { "matemáticas": 48, "física": 47, "química": 48, "biología": 48, "ciencias_de_la_tierra": 47 },
    "notas": { "matemáticas": 16, "física": 15, "química": 19, "biología": 18, "ciencias_de_la_tierra": 17 },
    "nombre_representante": "Victor Sandoval",
    "cedula_representante": "V-19456789",
    "fecha_nacimiento": "2007-03-20"
  },
  {
    "cedula": "V-16567890",
    "nombre": "Eric",
    "apellidos": "Rojas",
    "materias": ["Matemáticas", "Física", "Química", "Biología", "Ciencias de la Tierra"],
    "seccion": "A",
    "año": "5to Año",
    "genero": "Masculino",
    "estado": "Activo",
    "direccion": "Avenida Carabobo, Quinta La Esmeralda",
    "email": "eric.rojas@example.com",
    "asistencias": { "matemáticas": 48, "física": 49, "química": 48, "biología": 49, "ciencias_de_la_tierra": 48 },
    "notas": { "matemáticas": 15, "física": 19, "química": 18, "biología": 17, "ciencias_de_la_tierra": 16 },
    "nombre_representante": "Lara Rojas",
    "cedula_representante": "V-19567890",
    "fecha_nacimiento": "2007-06-25"
  },
  {
    "cedula": "V-15123456",
    "nombre": "Lola",
    "apellidos": "Pacheco",
    "materias": ["Matemáticas", "Física", "Química", "Inglés", "Filosofía"],
    "seccion": "B",
    "año": "5to Año",
    "genero": "Femenino",
    "estado": "Activo",
    "direccion": "Barrio Obrero, Carrera 18, #10-5",
    "email": "lola.pacheco@example.com",
    "asistencias": { "matemáticas": 47, "física": 48, "química": 47, "inglés": 48, "filosofía": 47 },
    "notas": { "matemáticas": 18, "física": 16, "química": 17, "inglés": 19, "filosofía": 15 },
    "nombre_representante": "Alex Pacheco",
    "cedula_representante": "V-14123456",
    "fecha_nacimiento": "2007-09-29"
  },
  {
    "cedula": "V-15234567",
    "nombre": "Martín",
    "apellidos": "Benitez",
    "materias": ["Matemáticas", "Física", "Química", "Inglés", "Filosofía"],
    "seccion": "B",
    "año": "5to Año",
    "genero": "Masculino",
    "estado": "Activo",
    "direccion": "Avenida Las Américas, Edificio Continental, Piso 3",
    "email": "martin.benitez@example.com",
    "asistencias": { "matemáticas": 48, "física": 48, "química": 48, "inglés": 48, "filosofía": 49 },
    "notas": { "matemáticas": 16, "física": 17, "química": 18, "inglés": 15, "filosofía": 19 },
    "nombre_representante": "Irene Benitez",
    "cedula_representante": "V-14234567",
    "fecha_nacimiento": "2007-12-03"
  },
  {
    "cedula": "V-15345678",
    "nombre": "Jimena",
    "apellidos": "Gallardo",
    "materias": ["Matemáticas", "Física", "Química", "Inglés", "Filosofía"],
    "seccion": "B",
    "año": "5to Año",
    "genero": "Femenino",
    "estado": "Activo",
    "direccion": "Urbanización Santa Cecilia, Calle 4, #11",
    "email": "jimena.gallardo@example.com",
    "asistencias": { "matemáticas": 47, "física": 46, "química": 47, "inglés": 47, "filosofía": 47 },
    "notas": { "matemáticas": 17, "física": 18, "química": 15, "inglés": 16, "filosofía": 20 },
    "nombre_representante": "Joel Gallardo",
    "cedula_representante": "V-14345678",
    "fecha_nacimiento": "2007-03-08"
  },
  {
    "cedula": "V-15456789",
    "nombre": "Enzo",
    "apellidos": "Arias",
    "materias": ["Matemáticas", "Física", "Química", "Inglés", "Filosofía"],
    "seccion": "B",
    "año": "5to Año",
    "genero": "Masculino",
    "estado": "Activo",
    "direccion": "Residencias El Pilar, Torre I, Apto 5-A",
    "email": "enzo.arias@example.com",
    "asistencias": { "matemáticas": 49, "física": 48, "química": 49, "inglés": 49, "filosofía": 49 },
    "notas": { "matemáticas": 19, "física": 15, "química": 16, "inglés": 18, "filosofía": 17 },
    "nombre_representante": "Marina Arias",
    "cedula_representante": "V-14456789",
    "fecha_nacimiento": "2007-06-12"
  },
  {
    "cedula": "V-15567890",
    "nombre": "Noa",
    "apellidos": "Vidal",
    "materias": ["Matemáticas", "Física", "Química", "Inglés", "Filosofía"],
    "seccion": "B",
    "año": "5to Año",
    "genero": "Femenino",
    "estado": "Activo",
    "direccion": "Avenida España, Edificio Central, Piso 9",
    "email": "noa.vidal@example.com",
    "asistencias": { "matemáticas": 47, "física": 47, "química": 47, "inglés": 48, "filosofía": 47 },
    "notas": { "matemáticas": 15, "física": 19, "química": 18, "inglés": 17, "filosofía": 16 },
    "nombre_representante": "Rubén Vidal",
    "cedula_representante": "V-14567890",
    "fecha_nacimiento": "2007-09-16"
  },
  {
    "cedula": "V-14123456",
    "nombre": "Hector",
    "apellidos": "Arias",
    "materias": ["Matemáticas", "Física", "Química", "Dibujo Técnico", "Sociología"],
    "seccion": "C",
    "año": "5to Año",
    "genero": "Masculino",
    "estado": "Activo",
    "direccion": "Calle Los Almendros, #10-15, La Popita",
    "email": "hector.arias@example.com",
    "asistencias": { "matemáticas": 48, "física": 47, "química": 48, "dibujo_técnico": 48, "sociología": 48 },
    "notas": { "matemáticas": 16, "física": 17, "química": 19, "dibujo_técnico": 18, "sociología": 15 },
    "nombre_representante": "Estela Arias",
    "cedula_representante": "V-13123456",
    "fecha_nacimiento": "2007-12-20"
  },
  {
    "cedula": "V-14234567",
    "nombre": "Cloe",
    "apellidos": "Santos",
    "materias": ["Matemáticas", "Física", "Química", "Dibujo Técnico", "Sociología"],
    "seccion": "C",
    "año": "5to Año",
    "genero": "Femenino",
    "estado": "Activo",
    "direccion": "Avenida Principal de Las Lomas, Quinta #3",
    "email": "cloe.santos@example.com",
    "asistencias": { "matemáticas": 47, "física": 46, "química": 47, "dibujo_técnico": 46, "sociología": 47 },
    "notas": { "matemáticas": 17, "física": 16, "química": 18, "dibujo_técnico": 15, "sociología": 20 },
    "nombre_representante": "Israel Santos",
    "cedula_representante": "V-13234567",
    "fecha_nacimiento": "2007-03-25"
  },
  {
    "cedula": "V-14345678",
    "nombre": "Guillermo",
    "apellidos": "Arias",
    "materias": ["Matemáticas", "Física", "Química", "Dibujo Técnico", "Sociología"],
    "seccion": "C",
    "año": "5to Año",
    "genero": "Masculino",
    "estado": "Activo",
    "direccion": "Residencias Santa Clara, Torre B, Apto 11-A",
    "email": "guillermo.arias@example.com",
    "asistencias": { "matemáticas": 49, "física": 48, "química": 49, "dibujo_técnico": 49, "sociología": 48 },
    "notas": { "matemáticas": 18, "física": 15, "química": 17, "dibujo_técnico": 20, "sociología": 16 },
    "nombre_representante": "Amparo Arias",
    "cedula_representante": "V-13345678",
    "fecha_nacimiento": "2007-06-29"
  },
  {
    "cedula": "V-14456789",
    "nombre": "Anna",
    "apellidos": "Arias",
    "materias": ["Matemáticas", "Física", "Química", "Dibujo Técnico", "Sociología"],
    "seccion": "C",
    "año": "5to Año",
    "genero": "Femenino",
    "estado": "Activo",
    "direccion": "Avenida Los Mangos, Edificio Los Girasoles, PB",
    "email": "anna.arias@example.com",
    "asistencias": { "matemáticas": 46, "física": 47, "química": 46, "dibujo_técnico": 47, "sociología": 46 },
    "notas": { "matemáticas": 15, "física": 18, "química": 16, "dibujo_técnico": 17, "sociología": 19 },
    "nombre_representante": "Sergio Arias",
    "cedula_representante": "V-13456789",
    "fecha_nacimiento": "2007-10-03"
  },
  {
    "cedula": "V-14567890",
    "nombre": "Alex",
    "apellidos": "Arias",
    "materias": ["Matemáticas", "Física", "Química", "Dibujo Técnico", "Sociología"],
    "seccion": "C",
    "año": "5to Año",
    "genero": "Masculino",
    "estado": "Activo",
    "direccion": "Final Calle 1, Casa #50, Barrio Sucre",
    "email": "alex.arias@example.com",
    "asistencias": { "matemáticas": 49, "física": 49, "química": 49, "dibujo_técnico": 50, "sociología": 49 },
    "notas": { "matemáticas": 19, "física": 16, "química": 18, "dibujo_técnico": 15, "sociología": 17 },
    "nombre_representante": "Consuelo Arias",
    "cedula_representante": "V-13567890",
    "fecha_nacimiento": "2007-01-07"
  }
];

export default estudiantes;